import 'package:flutter/material.dart';

class GiftData {
  static final Map<String, List<Map<String, dynamic>>> giftCategories = {
    'Romantic': [
      {
        'name': 'Red Rose',
        'price': 1.99,
        'icon': Icons.local_florist,
        'color': Colors.red,
        'coins': 10,
      },
      {
        'name': 'Bouquet',
        'price': 19.99,
        'icon': Icons.eco,
        'color': Colors.pink,
        'coins': 100,
      },
      {
        'name': 'Chocolate',
        'price': 4.99,
        'icon': Icons.cake,
        'color': Colors.brown,
        'coins': 25,
      },
      {
        'name': 'Diamond Ring',
        'price': 499.99,
        'icon': Icons.diamond,
        'color': Colors.blue,
        'coins': 2500,
      },
      {
        'name': 'Love Letter',
        'price': 0.99,
        'icon': Icons.mail,
        'color': Colors.redAccent,
        'coins': 5,
      },
      {
        'name': 'Romantic Dinner',
        'price': 99.99,
        'icon': Icons.restaurant,
        'color': Colors.purple,
        'coins': 500,
      },
    ],
    'Birthday': [
      {
        'name': 'Birthday Cake',
        'price': 29.99,
        'icon': Icons.cake,
        'color': Colors.pinkAccent,
        'coins': 150,
      },
      {
        'name': 'Balloons',
        'price': 9.99,
        'icon': Icons.celebration,
        'color': Colors.blueAccent,
        'coins': 50,
      },
      {
        'name': 'Gift Box',
        'price': 14.99,
        'icon': Icons.card_giftcard,
        'color': Colors.green,
        'coins': 75,
      },
      {
        'name': 'Party Hat',
        'price': 4.99,
        'icon': Icons.celebration_outlined,
        'color': Colors.yellow,
        'coins': 25,
      },
      {
        'name': 'Champagne',
        'price': 49.99,
        'icon': Icons.local_bar,
        'color': Colors.amber,
        'coins': 250,
      },
      {
        'name': 'Birthday Card',
        'price': 2.99,
        'icon': Icons.notes,
        'color': Colors.red,
        'coins': 15,
      },
    ],
    'Holiday': [
      {
        'name': 'Christmas Tree',
        'price': 39.99,
        'icon': Icons.park,
        'color': Colors.green,
        'coins': 200,
      },
      {
        'name': 'Holiday Gift',
        'price': 24.99,
        'icon': Icons.card_giftcard,
        'color': Colors.red,
        'coins': 125,
      },
      {
        'name': 'Fireworks',
        'price': 19.99,
        'icon': Icons.fireplace,
        'color': Colors.orange,
        'coins': 100,
      },
      {
        'name': 'Travel Ticket',
        'price': 199.99,
        'icon': Icons.airplane_ticket,
        'color': Colors.blue,
        'coins': 1000,
      },
      {
        'name': 'Snow Globe',
        'price': 14.99,
        'icon': Icons.ac_unit,
        'color': Colors.lightBlue,
        'coins': 75,
      },
      {
        'name': 'Holiday Card',
        'price': 3.99,
        'icon': Icons.notes,
        'color': Colors.redAccent,
        'coins': 20,
      },
    ],
    'Congratulations': [
      {
        'name': 'Trophy',
        'price': 29.99,
        'icon': Icons.emoji_events,
        'color': Colors.amber,
        'coins': 150,
      },
      {
        'name': 'Medal',
        'price': 19.99,
        'icon': Icons.military_tech,
        'color': Colors.yellow,
        'coins': 100,
      },
      {
        'name': 'Certificate',
        'price': 9.99,
        'icon': Icons.description,
        'color': Colors.white,
        'coins': 50,
      },
      {
        'name': 'Champagne',
        'price': 49.99,
        'icon': Icons.local_bar,
        'color': Colors.amber,
        'coins': 250,
      },
      {
        'name': 'Flowers',
        'price': 14.99,
        'icon': Icons.local_florist,
        'color': Colors.pink,
        'coins': 75,
      },
      {
        'name': 'Gift Card',
        'price': 24.99,
        'icon': Icons.card_giftcard,
        'color': Colors.purple,
        'coins': 125,
      },
    ],
    'Luxury': [
      {
        'name': 'Diamond',
        'price': 999.99,
        'icon': Icons.diamond,
        'color': Colors.blue,
        'coins': 5000,
      },
      {
        'name': 'Sports Car',
        'price': 4999.99,
        'icon': Icons.directions_car,
        'color': Colors.red,
        'coins': 25000,
      },
      {
        'name': 'Private Jet',
        'price': 9999.99,
        'icon': Icons.airplanemode_active,
        'color': Colors.blueAccent,
        'coins': 50000,
      },
      {
        'name': 'Yacht',
        'price': 7999.99,
        'icon': Icons.directions_boat,
        'color': Colors.white,
        'coins': 40000,
      },
      {
        'name': 'Mansion',
        'price': 19999.99,
        'icon': Icons.villa,
        'color': Colors.amber,
        'coins': 100000,
      },
      {
        'name': 'Crown',
        'price': 4999.99,
        'icon': Icons.workspace_premium,
        'color': Colors.yellow,
        'coins': 25000,
      },
    ],
    'Everyday': [
      {
        'name': 'Coffee',
        'price': 4.99,
        'icon': Icons.coffee,
        'color': Colors.brown,
        'coins': 25,
      },
      {
        'name': 'Lunch',
        'price': 12.99,
        'icon': Icons.lunch_dining,
        'color': Colors.orange,
        'coins': 65,
      },
      {
        'name': 'Book',
        'price': 9.99,
        'icon': Icons.menu_book,
        'color': Colors.blueGrey,
        'coins': 50,
      },
      {
        'name': 'Movie Ticket',
        'price': 14.99,
        'icon': Icons.movie,
        'color': Colors.purple,
        'coins': 75,
      },
      {
        'name': 'Music',
        'price': 1.99,
        'icon': Icons.music_note,
        'color': Colors.pink,
        'coins': 10,
      },
      {
        'name': 'Virtual Hug',
        'price': 0.00,
        'icon': Icons.favorite,
        'color': Colors.red,
        'coins': 0,
      },
    ],
  };
}