// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hApQpfW3mMZKqRd0dW2ZQkB-cYNkZUI',
    appId: '1:498478540409:web:27eb64954e2a7f442696a8',
    messagingSenderId: '498478540409',
    projectId: 'ongea-270f9',
    authDomain: 'ongea-270f9.firebaseapp.com',
    databaseURL: 'https://ongea-270f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ongea-270f9.firebasestorage.app',
    measurementId: 'G-DW1X3YMQJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyTrC7ReGvunG8ZXb9N4QmnEPnDpEH1U',
    appId: '1:498478540409:android:c7d540b985ee3fa32696a8',
    messagingSenderId: '498478540409',
    projectId: 'ongea-270f9',
    authDomain: 'ongea-270f9.firebaseapp.com', 
    databaseURL: 'https://ongea-270f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ongea-270f9.firebasestorage.app',
    measurementId: 'G-DW1X3YMQJM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfuVi1nbSwtOHrrUCKLwaTVaZ2krF_U8',
    appId: '1:498478540409:ios:2d9a78f41a21d0d02696a8',
    messagingSenderId: '498478540409',
    projectId: 'ongea-270f9',
    databaseURL: 'https://ongea-270f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ongea-270f9.firebasestorage.app',
    androidClientId: '498478540409-arei0hkcogc56m9bifj01ada5tpood99.apps.googleusercontent.com',
    iosClientId: '498478540409-cs0j7i6u6165s4gjsc1qflabdmp30n3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ongea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfuVi1nbSwtOHrrUCKLwaTVaZ2krF_U8',
    appId: '1:498478540409:ios:2d9a78f41a21d0d02696a8',
    messagingSenderId: '498478540409',
    projectId: 'ongea-270f9',
    databaseURL: 'https://ongea-270f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ongea-270f9.firebasestorage.app',
    androidClientId: '498478540409-arei0hkcogc56m9bifj01ada5tpood99.apps.googleusercontent.com',
    iosClientId: '498478540409-cs0j7i6u6165s4gjsc1qflabdmp30n3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ongea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0hApQpfW3mMZKqRd0dW2ZQkB-cYNkZUI',
    appId: '1:498478540409:web:d6e2b62dcc9195952696a8',
    messagingSenderId: '498478540409',
    projectId: 'ongea-270f9',
    authDomain: 'ongea-270f9.firebaseapp.com',
    databaseURL: 'https://ongea-270f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ongea-270f9.firebasestorage.app',
    measurementId: 'G-P21Y3GJPMZ',
  );
}
